#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  common/aws-validation/mirror-ecr-images-from-manifest.sh --image-manifest FILE [options]

Purpose:
  Create/retain ECR repositories and push source Docker images listed in an
  image manifest generated by `generate-ecr-container-overrides.sh`.

Options:
  --profile NAME           Default: ${AWS_PROFILE:-dev}
  --region REGION          Default: ${AWS_REGION:-ap-southeast-1}
  --image-manifest FILE    Required. TSV with source_image/repository_name/tag/ecr_image.
  --ec2-role-arn ARN       Optional. Add repository policy allowing this role to pull.
  --out-dir DIR            Default: ~/.AGENTS-temp/offline/ecr-image-mirror-<timestamp>
  --no-pull                Do not pull source images; require them to already exist locally.
  --dry-run                Write plan only; do not create/push.
  --help

The script intentionally does not delete ECR repositories.
EOF
}

die() {
  echo "ERROR: $*" >&2
  exit 1
}

need() {
  command -v "$1" >/dev/null 2>&1 || die "missing required tool: $1"
}

profile="${AWS_PROFILE:-dev}"
region="${AWS_REGION:-ap-southeast-1}"
image_manifest=""
ec2_role_arn=""
out_dir="$HOME/.AGENTS-temp/offline/ecr-image-mirror-$(date +%Y%m%d-%H%M%S)"
pull_source="true"
dry_run="false"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile) profile="${2:?missing --profile value}"; shift 2 ;;
    --region) region="${2:?missing --region value}"; shift 2 ;;
    --image-manifest) image_manifest="${2:?missing --image-manifest value}"; shift 2 ;;
    --ec2-role-arn) ec2_role_arn="${2:?missing --ec2-role-arn value}"; shift 2 ;;
    --out-dir) out_dir="${2:?missing --out-dir value}"; shift 2 ;;
    --no-pull) pull_source="false"; shift ;;
    --dry-run) dry_run="true"; shift ;;
    --help|-h) usage; exit 0 ;;
    *) die "unknown argument: $1" ;;
  esac
done

[[ -n "$image_manifest" && -f "$image_manifest" ]] || die "--image-manifest must be an existing file"

need docker
need jq
need python3

mkdir -p "$out_dir"
cp "$image_manifest" "$out_dir/image-manifest.tsv"

python3 - "$image_manifest" "$out_dir/manifest-validation.tsv" <<'PY'
import csv
import re
import sys

manifest, validation_out = sys.argv[1:]
repo_re = re.compile(r"^[a-z0-9]+([._/-]?[a-z0-9]+)*$")
tag_re = re.compile(r"^[A-Za-z0-9_][A-Za-z0-9_.-]{0,127}$")
ecr_re = re.compile(r"^(?P<registry>[0-9]{12}\.dkr\.ecr\.[A-Za-z0-9-]+\.amazonaws(?:\.com(?:\.cn)?|\.com))/(?:.+):.+$")
errors = []
rows = []

with open(manifest, newline="", encoding="utf-8") as handle:
    reader = csv.reader(handle, delimiter="\t")
    header = next(reader, None)
    if header != ["source_image", "repository_name", "tag", "ecr_image"]:
        errors.append(f"invalid header: {header}")
    for line_number, row in enumerate(reader, start=2):
        if len(row) != 4:
            errors.append(f"line {line_number}: expected 4 columns, got {len(row)}")
            continue
        source_image, repository_name, tag, ecr_image = [value.strip() for value in row]
        rows.append((line_number, source_image, repository_name, tag, ecr_image))
        if not source_image:
            errors.append(f"line {line_number}: source_image is empty")
        if not repo_re.match(repository_name) or len(repository_name) > 256:
            errors.append(f"line {line_number}: invalid repository_name: {repository_name}")
        if not tag_re.match(tag):
            errors.append(f"line {line_number}: invalid tag: {tag}")
        match = ecr_re.match(ecr_image)
        if not match:
            errors.append(f"line {line_number}: invalid ecr_image: {ecr_image}")
        else:
            expected_ecr_image = f"{match.group('registry')}/{repository_name}:{tag}"
            if ecr_image != expected_ecr_image:
                errors.append(
                    f"line {line_number}: ecr_image does not match repository_name/tag: {ecr_image}"
                )

with open(validation_out, "w", encoding="utf-8") as handle:
    handle.write("line\tsource_image\trepository_name\ttag\tecr_image\n")
    for row in rows:
        handle.write("\t".join(str(value) for value in row) + "\n")

if errors:
    for error in errors:
        print(error, file=sys.stderr)
    sys.exit(1)
PY

repository_policy="$out_dir/ecr-repository-policy.json"
if [[ -n "$ec2_role_arn" ]]; then
  jq -n --arg role "$ec2_role_arn" '{
    Version: "2012-10-17",
    Statement: [
      {
        Sid: "AllowValidationEc2Pull",
        Effect: "Allow",
        Principal: {AWS: $role},
        Action: [
          "ecr:BatchCheckLayerAvailability",
          "ecr:BatchGetImage",
          "ecr:GetDownloadUrlForLayer"
        ]
      }
    ]
  }' > "$repository_policy"
fi

account_id=""
registry=""
if [[ "$dry_run" != "true" ]]; then
  account_id="$(aws --profile "$profile" --region "$region" sts get-caller-identity --query Account --output text)"
  registry="$account_id.dkr.ecr.$region.amazonaws.com"
  aws --profile "$profile" --region "$region" ecr get-login-password \
    | docker login --username AWS --password-stdin "$registry" \
    > "$out_dir/ecr-login.txt"
fi

{
  echo "source_image	repository_name	tag	ecr_image	action"
  tail -n +2 "$image_manifest" | while IFS=$'\t' read -r source_image repository_name tag ecr_image; do
    [[ -n "$source_image" && -n "$repository_name" && -n "$tag" && -n "$ecr_image" ]] || continue
    echo "$source_image	$repository_name	$tag	$ecr_image	planned"
  done
} > "$out_dir/plan.tsv"

if [[ "$dry_run" == "true" ]]; then
  cat > "$out_dir/RESULT.md" <<RESULT
# RESULT - ECR Image Mirror

Status: dry_run

Manifest: \`$image_manifest\`

Evidence:
- \`$out_dir/plan.tsv\`
RESULT
  cat "$out_dir/RESULT.md"
  exit 0
fi

created_count=0
pushed_count=0
reused_count=0

while IFS=$'\t' read -r source_image repository_name tag ecr_image; do
  [[ -n "$source_image" && -n "$repository_name" && -n "$tag" && -n "$ecr_image" ]] || continue

  if aws --profile "$profile" --region "$region" ecr describe-repositories \
    --repository-names "$repository_name" \
    >> "$out_dir/ecr-describe-repositories.jsonl" 2>> "$out_dir/ecr-describe-repositories.stderr"; then
    reused_count=$((reused_count + 1))
  else
    aws --profile "$profile" --region "$region" ecr create-repository \
      --repository-name "$repository_name" \
      --image-scanning-configuration scanOnPush=false \
      --encryption-configuration encryptionType=AES256 \
      --tags \
        Key=Name,Value="$(basename "$repository_name")" \
        Key=dev,Value=amit \
        Key=project,Value=nextflow-offline \
        Key=created,Value="$(date +%F)" \
        Key=tools,Value=cdx \
        Key=environment,Value=dev \
        Key=owner,Value=amit \
        Key=version,Value=ecr-mirror \
        Key=TTL,Value=review-month-end \
        Key=purpose,Value=nextflow-offline-ecr-mirror \
        Key=phase,Value=ecr-pipeline-e2e \
        >> "$out_dir/ecr-create-repositories.jsonl" \
        2>> "$out_dir/ecr-create-repositories.stderr"
    created_count=$((created_count + 1))
  fi

  if [[ -n "$ec2_role_arn" ]]; then
    aws --profile "$profile" --region "$region" ecr set-repository-policy \
      --repository-name "$repository_name" \
      --policy-text "file://$repository_policy" \
      >> "$out_dir/ecr-set-repository-policies.jsonl" \
      2>> "$out_dir/ecr-set-repository-policies.stderr"
  fi

  if [[ "$pull_source" == "true" ]]; then
    docker pull "$source_image" >> "$out_dir/docker-pull.log" 2>> "$out_dir/docker-pull.stderr"
  fi
  inspect_file="$out_dir/docker-inspect-${pushed_count}.json"
  docker image inspect "$source_image" > "$inspect_file" 2>> "$out_dir/docker-inspect.stderr"
  docker tag "$source_image" "$ecr_image" >> "$out_dir/docker-tag.log" 2>> "$out_dir/docker-tag.stderr"
  docker push "$ecr_image" >> "$out_dir/docker-push.log" 2>> "$out_dir/docker-push.stderr"
  pushed_count=$((pushed_count + 1))
done < <(tail -n +2 "$image_manifest")

cat > "$out_dir/RESULT.md" <<RESULT
# RESULT - ECR Image Mirror

Status: pushed

Profile/region:
- $profile / $region

Counts:
- created_repositories: $created_count
- reused_repositories: $reused_count
- pushed_images: $pushed_count

Manifest:
- $image_manifest

Evidence:
- $out_dir/plan.tsv
- $out_dir/docker-pull.log
- $out_dir/docker-push.log
- $out_dir/ecr-create-repositories.jsonl
- $out_dir/ecr-set-repository-policies.jsonl

Cleanup:
- ECR repositories retained by design.
RESULT

cat "$out_dir/RESULT.md"
