bump_version: null
lint: null
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: Christopher Hakkaart
  description: An nf-core demo pipeline
  force: false
  is_nfcore: true
  name: demo
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.0.0
update: null
